import React, { Component } from 'react';
import {
    Image,
    View,
    Text,
    ScrollView,
    Dimensions
} from 'react-native';
import { Grid, Icon } from 'antd-mobile-rn';
import SplashScreen from "react-native-splash-screen"; 
import { IconFill, IconOutline } from "@ant-design/icons-react-native";

var iconfillarr = [
    "account-book",
    "alert",
    "alipay-circle",
    "alipay-square",
    "aliwangwang",
    "amazon-circle",
    "amazon-square",
    "android",
    "api",
    "apple",
    "appstore",
    "audio",
    "backward",
    "bank",
    "behance-circle",
    "behance-square",
    "bell",
    "book",
    "box-plot",
    "build",
    "bulb",
    "calculator",
    "calendar",
    "camera",
    "car",
    "caret-down",
    "caret-left",
    "caret-right",
    "caret-up",
    "carry-out",
    "check-circle",
    "check-square",
    "chrome",
    "ci-circle",
    "clock-circle",
    "close-circle",
    "close-square",
    "cloud",
    "code",
    "code-sandbox-circle",
    "code-sandbox-square",
    "codepen-circle",
    "codepen-square",
    "compass",
    "contacts",
    "container",
    "control",
    "copy",
    "copyright-circle",
    "credit-card",
    "crown",
    "customer-service",
    "dashboard",
    "database",
    "delete",
    "diff",
    "dingtalk-circle",
    "dingtalk-square",
    "dislike",
    "dollar-circle",
    "down-circle",
    "down-square",
    "dribbble-circle",
    "dribbble-square",
    "dropbox-circle",
    "dropbox-square",
    "edit",
    "environment",
    "euro-circle",
    "exclamation-circle",
    "experiment",
    "eye",
    "eye-invisible",
    "facebook",
    "fast-backward",
    "fast-forward",
    "file",
    "file-add",
    "file-excel",
    "file-exclamation",
    "file-image",
    "file-markdown",
    "file-pdf",
    "file-ppt",
    "file-text",
    "file-unknown",
    "file-word",
    "file-zip",
    "filter",
    "fire",
    "flag",
    "folder",
    "folder-add",
    "folder-open",
    "forward",
    "frown",
    "fund",
    "funnel-plot",
    "gift",
    "github",
    "gitlab",
    "golden",
    "google-circle",
    "google-plus-circle",
    "google-plus-square",
    "google-square",
    "hdd",
    "heart",
    "highlight",
    "home",
    "hourglass",
    "html5",
    "idcard",
    "ie-circle",
    "ie-square",
    "info-circle",
    "instagram",
    "insurance",
    "interation",
    "layout",
    "left-circle",
    "left-square",
    "like",
    "linkedin",
    "lock",
    "mail",
    "medicine-box",
    "medium-circle",
    "medium-square",
    "meh",
    "message",
    "minus-circle",
    "minus-square",
    "mobile",
    "money-collect",
    "notification",
    "pause-circle",
    "pay-circle",
    "phone",
    "picture",
    "pie-chart",
    "play-circle",
    "play-square",
    "plus-circle",
    "plus-square",
    "pound-circle",
    "printer",
    "profile",
    "project",
    "property-safety",
    "pushpin",
    "qq-circle",
    "qq-square",
    "question-circle",
    "read",
    "reconciliation",
    "red-envelope",
    "reddit-circle",
    "reddit-square",
    "rest",
    "right-circle",
    "right-square",
    "rocket",
    "safety-certificate",
    "save",
    "schedule",
    "security-scan",
    "setting",
    "shop",
    "shopping",
    "sketch-circle",
    "sketch-square",
    "skin",
    "skype",
    "slack-circle",
    "slack-square",
    "sliders",
    "smile",
    "snippets",
    "sound",
    "star",
    "step-backward",
    "step-forward",
    "stop",
    "switcher",
    "tablet",
    "tag",
    "tags",
    "taobao-circle",
    "taobao-square",
    "thunderbolt",
    "tool",
    "trademark-circle",
    "trophy",
    "twitter-circle",
    "twitter-square",
    "unlock",
    "up-circle",
    "up-square",
    "usb",
    "video-camera",
    "wallet",
    "warning",
    "wechat",
    "weibo-circle",
    "weibo-square",
    "windows",
    "yahoo",
    "youtube",
    "yuque",
    "zhihu-circle",
    "zhihu-square",
]

var iconoutlinearr = [
    "account-book",
  "alert",
  "alibaba",
  "align-center",
  "align-left",
  "align-right",
  "alipay",
  "alipay-circle",
  "aliwangwang",
  "aliyun",
  "amazon",
  "android",
  "ant-cloud",
  "ant-design",
  "apartment",
  "api",
  "apple",
  "appstore",
  "area-chart",
  "arrow-down",
  "arrow-left",
  "arrow-right",
  "arrow-up",
  "arrows-alt",
  "audio",
  "audit",
  "backward",
  "bank",
  "bar-chart",
  "barcode",
  "bars",
  "behance",
  "behance-square",
  "bell",
  "bg-colors",
  "block",
  "bold",
  "book",
  "border",
  "border-bottom",
  "border-horizontal",
  "border-inner",
  "border-left",
  "border-outer",
  "border-right",
  "border-top",
  "border-verticle",
  "box-plot",
  "branches",
  "build",
  "bulb",
  "calculator",
  "calendar",
  "camera",
  "car",
  "caret-down",
  "caret-left",
  "caret-right",
  "caret-up",
  "carry-out",
  "check",
  "check-circle",
  "check-square",
  "chrome",
  "ci",
  "clock-circle",
  "close",
  "close-circle",
  "close-square",
  "cloud",
  "cloud-download",
  "cloud-server",
  "cloud-sync",
  "cloud-upload",
  "cluster",
  "code",
  "code-sandbox",
  "codepen",
  "codepen-circle",
  "coffee",
  "colum-height",
  "column-width",
  "compass",
  "contacts",
  "container",
  "control",
  "copy",
  "copyright",
  "credit-card",
  "crown",
  "customer-service",
  "dash",
  "dashboard",
  "database",
  "delete",
  "deployment-unit",
  "desktop",
  "diff",
  "dingding",
  "disconnect",
  "dislike",
  "dollar",
  "dot-chart",
  "double-left",
  "double-right",
  "down",
  "down-circle",
  "down-square",
  "download",
  "drag",
  "dribbble",
  "dribbble-square",
  "dropbox",
  "edit",
  "ellipsis",
  "enter",
  "environment",
  "euro",
  "exception",
  "exclamation",
  "exclamation-circle",
  "experiment",
  "export",
  "eye",
  "eye-invisible",
  "facebook",
  "fall",
  "fast-backward",
  "fast-forward",
  "file",
  "file-add",
  "file-done",
  "file-excel",
  "file-exclamation",
  "file-image",
  "file-jpg",
  "file-markdown",
  "file-pdf",
  "file-ppt",
  "file-protect",
  "file-search",
  "file-sync",
  "file-text",
  "file-unknown",
  "file-word",
  "file-zip",
  "filter",
  "fire",
  "flag",
  "folder",
  "folder-add",
  "folder-open",
  "font-colors",
  "font-size",
  "fork",
  "form",
  "forward",
  "frown",
  "fullscreen",
  "fullscreen-exit",
  "fund",
  "funnel-plot",
  "gateway",
  "gift",
  "github",
  "gitlab",
  "global",
  "gold",
  "google",
  "google-plus",
  "hdd",
  "heart",
  "heat-map",
  "highlight",
  "home",
  "hourglass",
  "html5",
  "idcard",
  "ie",
  "import",
  "inbox",
  "info",
  "info-circle",
  "instagram",
  "insurance",
  "interation",
  "issues-close",
  "italic",
  "key",
  "laptop",
  "layout",
  "left",
  "left-circle",
  "left-square",
  "like",
  "line",
  "line-chart",
  "line-height",
  "link",
  "linkedin",
  "loading",
  "loading-3-quarters",
  "lock",
  "login",
  "logout",
  "mail",
  "man",
  "medicine-box",
  "medium",
  "medium-workmark",
  "meh",
  "menu",
  "menu-fold",
  "menu-unfold",
  "message",
  "minus",
  "minus-circle",
  "minus-square",
  "mobile",
  "money-collect",
  "monitor",
  "mr",
  "notification",
  "number",
  "ordered-list",
  "paper-clip",
  "pause",
  "pause-circle",
  "pay-circle",
  "percentage",
  "phone",
  "pic-center",
  "pic-left",
  "pic-right",
  "picture",
  "pie-chart",
  "play-circle",
  "play-square",
  "plus",
  "plus-circle",
  "plus-square",
  "pound",
  "poweroff",
  "printer",
  "profile",
  "project",
  "property-safety",
  "pushpin",
  "qq",
  "qrcode",
  "question",
  "question-circle",
  "radar-chart",
  "radius-bottomleft",
  "radius-bottomright",
  "radius-setting",
  "radius-upleft",
  "radius-upright",
  "read",
  "reconciliation",
  "red-envelope",
  "reddit",
  "redo",
  "reload",
  "reload-time",
  "rest",
  "retweet",
  "right",
  "right-circle",
  "right-square",
  "rise",
  "robot",
  "rocket",
  "rollback",
  "safety",
  "safety-certificate",
  "save",
  "scan",
  "schedule",
  "scissor",
  "search",
  "security-scan",
  "select",
  "setting",
  "shake",
  "share-alt",
  "shop",
  "shopping",
  "shopping-cart",
  "shrink",
  "sketch",
  "skin",
  "skype",
  "slack",
  "slack-square",
  "sliders",
  "small-dash",
  "smile",
  "snippets",
  "solution",
  "sort-ascending",
  "sort-descending",
  "sound",
  "star",
  "step-backward",
  "step-forward",
  "stock",
  "stop",
  "strikethrough",
  "swap",
  "swap-left",
  "swap-right",
  "switcher",
  "sync",
  "table",
  "tablet",
  "tag",
  "tags",
  "taobao",
  "taobao-circle",
  "team",
  "thunderbolt",
  "to-top",
  "tool",
  "trademark",
  "transaction",
  "trophy",
  "twitter",
  "underline",
  "undo",
  "unlock",
  "unordered-list",
  "up",
  "up-circle",
  "up-square",
  "upload",
  "usb",
  "user",
  "user-add",
  "user-delete",
  "usergroup-add",
  "usergroup-delete",
  "vertical-align-bottom",
  "vertical-align-middle",
  "vertical-align-top",
  "vertical-left",
  "vertical-right",
  "video-camera",
  "wallet",
  "warning",
  "wechat",
  "weibo",
  "weibo-circle",
  "weibo-square",
  "wifi",
  "windows",
  "woman",
  "yahoo",
  "youtube",
  "yuque",
  "zhihu",
  "zoom-in",
  "zoom-out",
]


var {height, width} =  Dimensions.get('window');

import * as action from '../actions';
import {connect} from 'react-redux';
import {bindActionCreators} from 'redux';

class Home extends Component {
    componentDidMount() {
        // 隐藏启动页，如果不设置消失时间，在组件加载完启动页自动隐藏
        setTimeout(() => {
            SplashScreen.hide();
        }, 3000);
    }

    static headersFind={
        headerTitle: 'Icon',
        headerRight:(
            <View>
                <Icon name="ellipsis" color="#FFF"/>
            </View>
        ),
        headerStyle: {
            backgroundColor: '#108ee9',
            height :height/15
        },
        headerTintColor: '#fff',
        headerTitleStyle: {
            fontWeight: 'bold',
            flex:1,
            textAlign: 'center'
        }
    };

    static navigationOptions = {
        title: 'Icon',
        tabBarIcon: ({ focused }) => {
            const icon = focused ? require('../images/home.png') : require('../images/home1.png');
            return <Image source={icon} style={{ height: 22, width: 22 }} />;
        },
    };
    
    onChange = (value) => {
        this.setState({ value });
    }

    constructor(props) {
        super(props);
        // this.navigation = props.navigation;
    }

    render() {
        // const iconfilldata = iconfillarr.map((_val, i) => ({
        //     icon: <IconFill name={_val} size={30}/>,
        //     text: _val,
        // }));
        const iconoutlinedata = iconoutlinearr.map((_val, i) => ({
            icon: <IconOutline name={_val} size={30}/>,
            text: _val,
        }));
        console.log(IconFill);
        const { actions, state, navigation } = this.props;
        return (
            <ScrollView>
                {/* <Text>IconFill</Text>
                <Grid data={iconfilldata} activeStyle={false} hasLine={false}/>
                <View style={{marginTop: 80}}></View> */}
                <Text>IconOutline</Text>
                <Grid data={iconoutlinedata} activeStyle={false} hasLine={false}/>
            </ScrollView>
        );
    }
}

export default connect(state => ({
	state: state.user
}), (dispatch) => ({
	actions: bindActionCreators(action.user, dispatch)
}))(Home);

const styles = {
    container: {
        flex: 1,
        backgroundColor: '#F5FCFF',
    }
};